# Inspired by https://github.com/openfaas/faas/blob/master/.github/workflows/publish.yml
name: publish

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */7 * *'  # 每隔7天的UTC时间午夜运行

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.TOKEN }}

      - name: Publish
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          outputs: "type=registry,push=true"
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: |
            madeliney/docker-static-website:latest
